hostname: 'ar14-cdn.thlon'
services:
  mcdn:
    tgref: 2578
    lag: 0
    remote_svr: 'FEBE-01'
    svc_id: 3
    range: C
    ipv4: '90.211.179.128/26'
    ipv6: '2a02:c7a:8000:120c::/64'
    array:
      1:
        port: '5/1/25'
        remote_port: '0/39'
      2:
        port: '5/1/26'
        remote_port: '0/40'
      3:
        port: '5/1/27'
        remote_port: '0/41'
      4:
        port: '5/1/28'
        remote_port: '0/42'
      5:
        port: '5/1/29'
        remote_port: '0/43'
      6:
        port: '5/1/30'
        remote_port: '0/44'
      7:
        port: '5/1/31'
        remote_port: '0/45'
      8:
        port: '5/1/32'
        remote_port: '0/46'
      9:
        port: '5/1/33'
        remote_port: '0/47'
      0:
        port: '5/1/34'
        remote_port: '0/48'
