system_address                       : 84.38.34.170
#LAST OCTET IS USED TO CALCULATE BUNDLE-ID.
#IF LOOPBACK IS IN RANGE:"84.38.34.0/24", THEN PLEASE INPUT THE LAST OCTET AND IT WILL ADD 256 TO THAT NUMBER FOR THE BUNDLE-ID.
#IF LOOPBACK IS IN RANGE:"89.200.128.0/24", THEN PLEASE INPUT THE LAST OCTET -256 BELOW SO THAT IT WILL USE THE LAST OCTET ITSELF AS THE BUNDLE-ID.
last_octet_system_address            : 170
node_name                            : sr12.enntg
dcn_primary_address                  : "10.200.168.116/24"
dcn_secondary_address                : "10.200.168.117/24"
location                             : 'Rack SUITE B RACK 12, Console: 10.200.168.100, port 15 (SFM A) / port 16 (SFM B)'

rr0_bllon_bgp_password               : fWJzj2caZbw7Nr5X
rr0_enlba_bgp_password               : f7hnXZPEOjLUlGbH
rr1_bllon_bgp_password               : MwmZLpeXdJUE8BkP
rr1_enlba_bgp_password               : KKIBC2ipXcjjqrzB
rr3_bllon_bgp_password               : i0RI3W2K6F0MfhaV
rr3_enlba_bgp_password               : QwPfpnVvXX06UaOV

ar0_isp_bllon_bgp_password           : KOHe8rFXXdBpK9AV
ar0_isp_enlba_bgp_password           : erzU2q1z2ETFa9ym
ar0_isp_enshf_bgp_password           : IdjcGxBJlhrp7q3N
ar0_isp_enbgk_bgp_password           : 5PyWv1gVcbdDazyu
ar0_isp_hobir_bgp_password           : DBhcZCEJsfOjglN8

ironman_bllon_policy                 : 3RD
ironman_enbgk_policy                 : REST
ironman_enlba_policy                 : 1ST
ironman_enshf_policy                 : REST
ironman_hobir_policy                 : 2ND

tacacs_secret                        : wIJa4jOBxQQwXDwJ

p_router_1_hostname                  : pr2.enlba
p_router_2_hostname                  : pr3.thlon

core_1:
  1:
    core: "Te0/7/0/8/2"
    bbpe: "1/1/1"
    cid: "1000/LDSA-NGMA/10GLAN/OVN13"
  2:
    core: "Te0/7/0/8/1"
    bbpe: "1/1/2"
    cid: "1000/LDSA-NGMA/10GLAN/OVN14"
  3:
    core: "Te0/7/0/8/0"
    bbpe: "1/1/3"
    cid: "1000/LDSA-NGMA/10GLAN/OVN15"

core_2:
  1:
    core: "Te0/1/0/9/9"
    bbpe: "9/1/1"
    cid: "1000/LNTN-NGMA/10GLAN/OVN13"
  2:
    core: "Te0/1/0/9/8"
    bbpe: "9/1/2"
    cid: "1000/LNTN-NGMA/10GLAN/OVN14"
  3:
    core: "Te0/1/0/9/7"
    bbpe: "9/1/3"
    cid: "1000/LNTN-NGMA/10GLAN/OVN15"

core_1_p2p: "84.38.37.150/31"
core_2_p2p: "84.38.37.152/31"

p_router_1_isis_key_1                : CP6enWzpGpLHruO2
p_router_2_isis_key_1                : zjbz29AEeExuugxR

p_router_1_loopback0                 : 89.200.128.103
p_router_2_loopback0                 : 89.200.128.112

p_router_1_ldp_key                   : p8u9p0LXglFFZIW0
p_router_2_ldp_key                   : WZKnNTDAyM6rGmq8

ar4_bllon_ldpkey                     : JxY0wNJkgXCAcSHz
ar0_enlba_ldpkey                     : 9hiFYsjFLb9WZ81n

sed_vlanid                           : 3617
sed_remote_site_code                 : STKA
distbng_unnumbered_address           : 90.208.114.200
distbng_ipv6_subscribers_range       : "2a02:c7d:de00::/39"

br0_hobir_ldp_key                    : OKh34A8gNplR1T4y
br0_bllon_ldp_key                    : zkcO7brFAwQb3cKc
br0_thlon_ldp_key                    : lDpASBCbpV0j7phq
br0_enlba_ldp_key                    : SVLZnlpd9UIW0iXV

distgea_interface                    : 90.208.114.201
distgea_sub_gi_address               : 151.231.254.240
distgea_ipv6_subscribers_range       : "2a02:c7f:da00::/39"
#THE BELOW IS ALWAYS LAST_OCTET OF SYSTEM ADDRESS + 256
vc_id                                : 426

precedence_1                         : primary
precedence_2                         : 1

u_bend_port_1: "9/1/6"
u_bend_port_2: "9/2/1"