---
#device information
site_id: enyrk
site_community: 14436
hostname: ar11-cdn.enyrk
loopback: "89.200.128.53/32"
location: York

# Netflix services
ntf:
  farm: A
  ipv4: "90.223.190.176/28"
  v4_entry: 24
  ipv6: "2A02:C7A:8000:1007::/64"
  v6_entry: 293
  ies: 220400
  vpls: 220401
  array:
    30:
      1:
        port: 5/1/3
        server_id: "A"
        link_no: 1
      2:
        port: 5/1/4
        server_id: "A"
        link_no: 2

    31:
      1:
        port: 5/1/5
        server_id: "B"
        link_no: 1
      2:
        port: 5/1/6
        server_id: "B"
        link_no: 2

    32:
      1:
        port: 5/1/7
        server_id: "C"
        link_no: 1
      2:
        port: 5/1/8
        server_id: "C"
        link_no: 2
