---

- name: Generate CDN configuration files
  hosts: localhost
  gather_facts: no
  connection: local

  vars_files:
    - roles/common/vars/sites/hobir.yml
    - roles/cdn-sr12e_migration/vars/hobir.yml

  roles:
    - cdn-sr12e_migration
